--3. CARGA: MODELO ESTRELLA 
---3.1 CREAR LA TABLA DE DIMENSIONES: DIM_ACCOUNT

CREATE TABLE DIM_ACCOUNT (
    Account_ID INTEGER PRIMARY KEY AUTOINCREMENT, -- Clave primaria única
    NAME VARCHAR(255) NOT NULL,                  -- Nombre de la cuenta
    COUNTRY VARCHAR(255),                        -- País asociado
    TOPIC_OF_INFLUENCE VARCHAR(255),             -- Tema de influencia
    PLATFORM VARCHAR(50) NOT NULL               -- Fuente: THREADS o INSTAGRAM
);

---3.2 CREAR TABLA DE HECHOS: FACT_SOCIAL_METRICS 

CREATE TABLE FACT_SOCIAL_METRICS (
    Metric_ID INTEGER PRIMARY KEY AUTOINCREMENT, -- Identificador único
    Account_ID INTEGER NOT NULL,                 -- Clave foránea hacia DIM_ACCOUNT
    NAME VARCHAR(255) NOT NULL,                  -- Nombre de la cuenta
    PLATFORM VARCHAR(50) NOT NULL,               -- Origen de los datos: THREADS o INSTAGRAM
    FOLLOWERS INTEGER,                           -- Número de seguidores
    POTENTIAL_REACH INTEGER,                     -- Alcance potencial
    ENGAGEMENT DECIMAL(10, 2),                   -- Interacción calculada (FOLLOWERS * ER)
    ER DECIMAL(5, 4),                            -- Tasa de interacción
    FOREIGN KEY (Account_ID) REFERENCES DIM_ACCOUNT(Account_ID) -- Relación con DIM_ACCOUNT
);

---3.3 INSERTAMOS DATOS EN DIM_ACCOUNT 

--THREADS

INSERT INTO DIM_ACCOUNT (NAME, COUNTRY, TOPIC_OF_INFLUENCE, PLATFORM)
SELECT NAME, COUNTRY, TOPIC_OF_INFLUENCE, 'THREADS' AS PLATFORM
FROM THREADS;

-- INSTAGRAM 

INSERT INTO DIM_ACCOUNT (NAME, COUNTRY, TOPIC_OF_INFLUENCE, PLATFORM)
SELECT NAME, COUNTRY, TOPIC_OF_INFLUENCE, 'INSTAGRAM' AS PLATFORM
FROM INSTAGRAM;

-- 3.4 CONSULTAR EL MODELO DIMENSIONAL 

--consultar metricas entre fuentes

SELECT d.NAME, d.PLATFORM, f.FOLLOWERS, f.POTENTIAL_REACH, f.ENGAGEMENT, f.ER
FROM FACT_SOCIAL_METRICS f
JOIN DIM_ACCOUNT d ON f.Account_ID = d.Account_ID
ORDER BY d.NAME, d.PLATFORM;

--resumir datos por plataforma 

SELECT d.PLATFORM, SUM(f.FOLLOWERS) AS TOTAL_FOLLOWERS, SUM(f.ENGAGEMENT) AS TOTAL_ENGAGEMENT
FROM FACT_SOCIAL_METRICS f
JOIN DIM_ACCOUNT d ON f.Account_ID = d.Account_ID
GROUP BY d.PLATFORM;

-- analizar usuarios con presencia en ambas plataformas 

SELECT d.NAME, COUNT(DISTINCT d.PLATFORM) AS PLATFORM_COUNT
FROM DIM_ACCOUNT d
GROUP BY d.NAME
HAVING PLATFORM_COUNT > 1;

---3.5 INSERTAMOS DATOS EN FACT_SOCIAL_METRICS


--THREADS
INSERT INTO FACT_SOCIAL_METRICS (Account_ID, NAME, PLATFORM, FOLLOWERS, POTENTIAL_REACH, ENGAGEMENT, ER)
SELECT 
    (SELECT Account_ID FROM DIM_ACCOUNT WHERE NAME = t.NAME AND PLATFORM = 'THREADS') AS Account_ID,
    t.NAME, -- Nombre de la cuenta
    'THREADS' AS PLATFORM,
    t.FOLLOWERS,
    t.POTENTIAL_REACH,
    t.ENGAGEMENT,
    t.ER
FROM THREADS t;


--INSTAGRAM 
INSERT INTO FACT_SOCIAL_METRICS (Account_ID, NAME, PLATFORM, FOLLOWERS, POTENTIAL_REACH, ENGAGEMENT, ER)
SELECT 
    (SELECT Account_ID FROM DIM_ACCOUNT WHERE NAME = i.NAME AND PLATFORM = 'INSTAGRAM') AS Account_ID,
    i.NAME, -- Nombre de la cuenta
    'INSTAGRAM' AS PLATFORM,
    i.FOLLOWERS,
    i.POTENTIAL_REACH,
    i.ENGAGEMENT,
    i.ER
FROM INSTAGRAM i;

SELECT * FROM FACT_SOCIAL_METRICS;
