-- 1.EXTRACCION 

select * from THREADS;
select * from INSTAGRAM;
--- 1.1 RESUMEN GENERAL DE LOS DATOS 

----1.1.1 CONTEO TOTAL DE LOS REGISTROS

--THREADS 

SELECT COUNT(*) AS Total_Records_Threads FROM THREADS;

--INSTAGRAM 

SELECT COUNT(*) AS Total_Records_Instagram FROM INSTAGRAM;

----1.1.2 ANALISIS COMPARATIVO ENTRE PLATAFORMAS 

-- Comparar serguidores totales 


SELECT 'THREADS' AS Platform, SUM(FOLLOWERS) AS Total_Followers FROM THREADS
UNION ALL
SELECT 'INSTAGRAM' AS Platform, SUM(FOLLOWERS) AS Total_Followers FROM INSTAGRAM;

-- Tasa de interaccion orimedio por plataforma 

SELECT 'THREADS' AS Platform, AVG(ER) AS Avg_Engagement_Rate FROM THREADS
UNION ALL
SELECT 'INSTAGRAM' AS Platform, AVG(ER) AS Avg_Engagement_Rate FROM INSTAGRAM;

-- distribucion de usuarios por categorias de tamaño

SELECT 'THREADS' AS Platform, 
       CASE 
           WHEN FOLLOWERS < 1000 THEN 'Nano'
           WHEN FOLLOWERS BETWEEN 1000 AND 10000 THEN 'Micro'
           WHEN FOLLOWERS BETWEEN 10000 AND 100000 THEN 'Small'
           WHEN FOLLOWERS BETWEEN 100000 AND 1000000 THEN 'Medium'
           ELSE 'Large'
       END AS Size_Category,
       COUNT(*) AS Total_Users
FROM THREADS
GROUP BY Size_Category
UNION ALL
SELECT 'INSTAGRAM' AS Platform, 
       CASE 
           WHEN FOLLOWERS < 1000 THEN 'Nano'
           WHEN FOLLOWERS BETWEEN 1000 AND 10000 THEN 'Micro'
           WHEN FOLLOWERS BETWEEN 10000 AND 100000 THEN 'Small'
           WHEN FOLLOWERS BETWEEN 100000 AND 1000000 THEN 'Medium'
           ELSE 'Large'
       END AS Size_Category,
       COUNT(*) AS Total_Users
FROM INSTAGRAM
GROUP BY Size_Category;

--1.2 ANALISIS DE PAISES Y TEMAS DE INFLUENCIA 

--1.2.1 TOP 5 PAISES CON MAS SEGUIDORES 

--THREADS

SELECT COUNTRY, SUM(FOLLOWERS) AS Total_Followers
FROM THREADS
GROUP BY COUNTRY
ORDER BY Total_Followers DESC
LIMIT 5;

--INSTAGRAM

SELECT COUNTRY, SUM(FOLLOWERS) AS Total_Followers
FROM INSTAGRAM
GROUP BY COUNTRY
ORDER BY Total_Followers DESC
LIMIT 5;

--1.2.2 DISTRIBUCION DE TEMAS DE INFLUENCIA 

--THREADS

SELECT TOPIC_OF_INFLUENCE, COUNT(*) AS Total_Users
FROM THREADS
GROUP BY TOPIC_OF_INFLUENCE
ORDER BY Total_Users DESC;

--INSTAGRAM

SELECT TOPIC_OF_INFLUENCE, COUNT(*) AS Total_Users
FROM INSTAGRAM
GROUP BY TOPIC_OF_INFLUENCE
ORDER BY Total_Users DESC;

-- 1.3 USUARIOS COMPARTIDOS ENTRE PLATAFORMAS

SELECT t.NAME
FROM THREADS t
INNER JOIN INSTAGRAM i ON t.NAME = i.NAME;

--1.4 COMPARACION DE METRICAS ENTRE PLATAFORMAS

SELECT t.NAME, t.FOLLOWERS AS THREADS_FOLLOWERS, i.FOLLOWERS AS INSTAGRAM_FOLLOWERS,
       t.ER AS THREADS_ER, i.ER AS INSTAGRAM_ER
FROM THREADS t
INNER JOIN INSTAGRAM i ON t.NAME = i.NAME
ORDER BY t.NAME;




